### ISSUE TITLE
直接部署后无法上传文件

### ISSUE THREAD

**Issue by cnmstudio** [tongchengbin/ocean_ctf#12]
Exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/api/sys/views.py", line 72, in upload_file
    file.save(file_path)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/datastructures.py", line 3066, in save
    dst = open(dst, "wb")
PermissionError: [Errno 13] Permission denied: '/opt/ocean_ctf/upload/13210420-879f-4962-9edf-6e4a3de81ac9.tar'

这个应该是没有权限写入，但是，不知道该怎么给这个docker内部文件权限，

**Comment by cnmstudio** [comment]
selinux未关闭导致……
