### ISSUE TITLE
平台登录不进去

### ISSUE THREAD

**Issue by lhy879486978** [tongchengbin/ocean_ctf#45]
<img width="881" alt="image" src="https://github.com/tongchengbin/ocean_ctf/assets/120021090/d053dee5-baa7-4467-aaa2-856a44137f10">

用户前台服务器繁忙

<img width="1268" alt="image" src="https://github.com/tongchengbin/ocean_ctf/assets/120021090/9cdec367-131c-4710-a730-4615e565c80c">

后台管理登录后无跳转

**Comment by lhy879486978** [comment]
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.8.8 (default, Mar 31 2021, 12:29:49)  [GCC 8.3.0]
Python main interpreter initialized at 0x564787c01b30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 2)
Python auto-reloader enabled
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.DataError: (1406, "Data too long for column 'password' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    app = create_app()
  File "./app/__init__.py", line 46, in create_app
    create_default_data()
  File "./app/__init__.py", line 151, in create_default_data
    db.session.commit()
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.DataError: (MySQLdb.DataError) (1406, "Data too long for column 'password' at row 1")
[SQL: INSERT INTO s_admin (date_created, date_modified, username, password, role_id, active, login_time, token) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2024, 2, 26, 17, 42, 23, 494938), datetime.datetime(2024, 2, 26, 17, 42, 23, 494964), 'admin', 'scrypt:32768:8:1$dpJA1WX0Iaiknl10$91b72a8df8c077c6b9794ad432ef6178162ee6e124f754717814046788900f8eb8c652cc2424602a092ad3a6cff9d9ef0daa88021b210367178831de8a5314c0', 1, None, None, None)]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
SIGINT/SIGTERM received...killing workers...
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 1355, in _shutdown
    def _shutdown():
KeyboardInterrupt:
OOPS ! failed loading app in worker 1 (pid 7)
Mon Feb 26 17:42:24 2024 - need-app requested, destroying the instance...
goodbye to uWSGI.

**Comment by tongchengbin** [comment]
更新代码
```
docker compose down
docker compose up
```
