### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by linnn-xiinn** [tongchengbin/ocean_ctf#6]
用docker搭建完成之后显示Internal Server Error怎么办？

**Comment by linnn-xiinn** [comment]
使用docker搭建的，其中docker logs web的日志如下：
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    register_blueprints(app)
  File "./app/__init__.py", line 101, in register_blueprints
    from app.api.docker.views import bp as admin_docker_bp
  File "./app/api/docker/views.py", line 13, in <module>
    from app.tasks import task_docker
  File "./app/tasks/__init__.py", line 4, in <module>
    from app.tasks.ctf import *
  File "./app/tasks/ctf.py", line 8, in <module>
    from app.models.ctf import ContainerResource,User
ImportError: cannot import name 'User' from 'app.models.ctf' (./app/models/ctf.py)
unable to load app 0 (mountpoint='') (callable not found or import error)

**Comment by linnn-xiinn** [comment]
将app/tasks/ctf.py 文件中的from app.models.ctf import ContainerResource,User
修改为：
from app.models.ctf import ContainerResource
from app.models.user import Use
